source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in ttevents.gemspec
gemspec
gem "nokogiri"
# gem "open-uri"
gem "require_all"
